In [14]:
import pandas as pd
df = pd.read_csv("data.csv")
print(df)
print(df.head())
print(df.info())
print(type(df))

          day  temp  windspeed  humidity  event
0  01-01-2007    32          6        20   rain
1  01-02-2017    35          7        30  sunny
2  04-05-2017    28          2        45   snow
3  01-04-2017    24          7        40   snow
4  01-05-2017    32          4        25   rain
5  01-06-2017    31          2        20  sunny
          day  temp  windspeed  humidity  event
0  01-01-2007    32          6        20   rain
1  01-02-2017    35          7        30  sunny
2  04-05-2017    28          2        45   snow
3  01-04-2017    24          7        40   snow
4  01-05-2017    32          4        25   rain
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   day        6 non-null      object
 1   temp       6 non-null      int64
 2   windspeed  6 non-null      int64
 3   humidity   6 non-null      int64
 4   event      6 non-null      object
dtypes: int64(3), object(2)
memory usage: 368.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>

In [18]:
import pandas as pd

weather_data = [
    ['01-01-2017', 32, 6, 20, 'rain'], 
    ['01-02-2017', 35, 7, 30, 'sunny'], 
    ['04-05-2017', 28, 2, 45, 'snow'], 
    ['01-04-2017', 24, 7, 40, 'snow'], 
    ['01-05-2017', 32, 4, 25, 'rainy'], 
    ['01-06-2017', 31, 2, 20, 'sunny']
]

df = pd.DataFrame(weather_data, columns=['day', 'temp', 'windspeed', 'humidity', 'event'])

print(df)

          day  temp  windspeed  humidity  event
0  01-01-2017    32          6        20   rain
1  01-02-2017    35          7        30  sunny
2  04-05-2017    28          2        45   snow
3  01-04-2017    24          7        40   snow
4  01-05-2017    32          4        25  rainy
5  01-06-2017    31          2        20  sunny

### Work with Rows and Coloumn

In [35]:
print(df.shape) # for row coloumn 
print(df.columns)    # for printing differnt column
print(df.head)        # print first 5 rows (by default if (df.head(n))) print n rows
print(df.head(1))

(6, 5)
Index(['day', 'temp', 'windspeed', 'humidity', 'event'], dtype='object')
<bound method NDFrame.head of           day  temp  windspeed  humidity  event
0  01-01-2017    32          6        20   rain
1  01-02-2017    35          7        30  sunny
2  04-05-2017    28          2        45   snow
3  01-04-2017    24          7        40   snow
4  01-05-2017    32          4        25  rainy
5  01-06-2017    31          2        20  sunny>
          day  temp  windspeed  humidity event
0  01-01-2017    32          6        20  rain

In [37]:
print(df.tail(2))  # print last n rows

          day  temp  windspeed  humidity  event
4  01-05-2017    32          4        25  rainy
5  01-06-2017    31          2        20  sunny

In [38]:
# printing any random 3 sampel in daata set
df.sample(3)

          day  temp  windspeed  humidity  event
1  01-02-2017    35          7        30  sunny
2  04-05-2017    28          2        45   snow
0  01-01-2017    32          6        20   rain

In [39]:
# print data of a single column
df['day']

0    01-01-2017
1    01-02-2017
2    04-05-2017
3    01-04-2017
4    01-05-2017
5    01-06-2017
Name: day, dtype: object

In [41]:
df.day

0    01-01-2017
1    01-02-2017
2    04-05-2017
3    01-04-2017
4    01-05-2017
5    01-06-2017
Name: day, dtype: object

In [45]:
# print data of a multple column
df[['day','temp']]

          day  temp
0  01-01-2017    32
1  01-02-2017    35
2  04-05-2017    28
3  01-04-2017    24
4  01-05-2017    32
5  01-06-2017    31

In [46]:
print(df.temp)

0    32
1    35
2    28
3    24
4    32
5    31
Name: temp, dtype: int64

In [52]:
# mathematical opertaion
df['temp'].describe()

count     6.000000
mean     30.333333
std       3.829708
min      24.000000
25%      28.750000
50%      31.500000
75%      32.000000
max      35.000000
Name: temp, dtype: float64

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   day        6 non-null      object
 1   temp       6 non-null      int64
 2   windspeed  6 non-null      int64
 3   humidity   6 non-null      int64
 4   event      6 non-null      object
dtypes: int64(3), object(2)
memory usage: 368.0+ bytes

In [55]:
df.isnull()

     day   temp  windspeed  humidity  event
0  False  False      False     False  False
1  False  False      False     False  False
2  False  False      False     False  False
3  False  False      False     False  False
4  False  False      False     False  False
5  False  False      False     False  False

In [62]:
# indexing
print(df.iloc[2 , 4]) #position based
print('---------')
df.loc[2, 'event'] #label based

snow
---------

'snow'

### Operations

In [63]:
# print max temp
df['temp'].max()

35

In [64]:
# print the min temp
df['temp'].min()

24

In [68]:
# print standard daviation
round(df['temp'].std(),2)

3.83

In [81]:
# print row containg max temp
print(df[df.temp == df.temp.max()])

# print row containg minimum temp
print(df[df.temp == df.temp.min()])

1    7
Name: windspeed, dtype: int64

In [82]:
# print windspped containg max temp
print(df.windspeed[df.temp == df.temp.max()])

1    7
Name: windspeed, dtype: int64

In [84]:
df.index #show starting and ending point

RangeIndex(start=0, stop=6, step=1)

In [88]:
# set day as index
df.set_index('day')

            temp  windspeed  humidity  event
day
01-01-2017    32          6        20   rain
01-02-2017    35          7        30  sunny
04-05-2017    28          2        45   snow
01-04-2017    24          7        40   snow
01-05-2017    32          4        25  rainy
01-06-2017    31          2        20  sunny

In [94]:
# set day as index also moidfy the orginal
# df.set_index('day',inplace =True)

In [93]:
df

            temp  windspeed  humidity  event
day
01-01-2017    32          6        20   rain
01-02-2017    35          7        30  sunny
04-05-2017    28          2        45   snow
01-04-2017    24          7        40   snow
01-05-2017    32          4        25  rainy
01-06-2017    31          2        20  sunny

In [95]:
# reset index
df.reset_index(inplace=True)

In [96]:
df

          day  temp  windspeed  humidity  event
0  01-01-2017    32          6        20   rain
1  01-02-2017    35          7        30  sunny
2  04-05-2017    28          2        45   snow
3  01-04-2017    24          7        40   snow
4  01-05-2017    32          4        25  rainy
5  01-06-2017    31          2        20  sunny

In [101]:
# Shorying a val in particular column
df.sort_values(['temp'])

          day  temp  windspeed  humidity  event
3  01-04-2017    24          7        40   snow
2  04-05-2017    28          2        45   snow
5  01-06-2017    31          2        20  sunny
0  01-01-2017    32          6        20   rain
4  01-05-2017    32          4        25  rainy
1  01-02-2017    35          7        30  sunny